version: '3.1'

services:
  tensorboard:
    image: tensorflow/tensorflow
    restart: always
    ports:
    - "6006:6006"
    volumes:
    - ./runs:/root
    working_dir: /root
    command: tensorboard --logdir /root --bind_all
